In [42]:
#Import all required modules
import pandas
import neattext.functions as nt_func
import numpy
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from keybert import KeyBERT
import json

In [3]:
#Create a dataframe reading the csv file dataset
dataframe = pandas.read_csv("dataset/courses.csv")

#Simplified course names
dataframe["Simplified_Title"] = dataframe["course_title"].apply(nt_func.remove_stopwords)
dataframe["Simplified_Title"] = dataframe["Simplified_Title"].apply(nt_func.remove_special_characters)
dataframe["Simplified_Title"] = dataframe['Simplified_Title'].str.lower()
dataframe["course_title_l"] = dataframe["course_title"].str.lower()

#Text Vectorization Process
cvector = CountVectorizer()
cvector_matrix = cvector.fit_transform(dataframe['Simplified_Title'])

#building cosine similarity matrix
cossim_matrix = cosine_similarity(cvector_matrix)
#Getting course id
course_id = pandas.Series(dataframe.index, index=dataframe['course_title_l']).drop_duplicates()

In [12]:
#Recommendation System Function
def recommendation_system(user_input):
    #Check is user input is empty
    if user_input =='':
        user_input = None
 

    #Get course id
    if user_input is not None:

        user_input = user_input.lower()
        id = course_id[user_input]

        #create similarity index for each course and sorting from highest to lowest
        sim_index = list(enumerate(cossim_matrix[id]))
        sorted_sindex = sorted(sim_index, key=lambda x:x[1],reverse = True)
        sorted_sindex[1:]

        #Picking Final courses to be displayed:
        final_courses = [i[0] for i in sorted_sindex[1:]]
        
            
        #final result
        result = dataframe['course_title_l'].iloc[final_courses]
        result_dataframe = pandas.DataFrame(result)
        print(result_dataframe)

In [ ]:
recommendation_system("Python")

In [43]:
kw_model = KeyBERT(model='all-mpnet-base-v2')

In [100]:


df = pandas.DataFrame({
        'Courses':["Spark","PySpark","Python","pandas"],
        'Fee' :[20000,25000,22000,30000],
        'Duration':['30days','40days','35days','50days'],
        'Discount':[1000,2300,1200,2000]
})
df
title_index = df.index[df["Courses"] == "Spark"].tolist()
print(title_index)

[0]

In [111]:
technologies = {
        'Courses':["Spark","PySpark","Python","pandas"],
        'Fee' :[20000,25000,22000,30000],
        'Duration':['30days','40days','35days','50days'],
        'Discount':[1000,2300,1200,2000]
               }
df = pandas.DataFrame(technologies)
title_index = df.index[df["Courses"] == "PySpark"].tolist()
title_index = title_index[0]
df.at[title_index, 'Duration'] = ['30days', '35days']
print(df)

   Courses    Fee          Duration  Discount
0    Spark  20000            30days      1000
1  PySpark  25000  [30days, 35days]      2300
2   Python  22000            35days      1200
3   pandas  30000            50days      2000

In [ ]:

keywords = kw_model.extract_keywords("ultimate investment banking course", keyphrase_ngram_range=(1,3), stop_words="english", highlight =False, top_n=10)
keywords_list = list(dict(keywords).keys())
    #print(keywords_list)
title_index = dataframe.index[dataframe["course_title_l"] == "ultimate investment banking course"].tolist()
title_index = title_index[0]
dataframe['keywords'] = ""
for i in range(2):
    dataframe.at[i,"keywords"] = keywords_list

dataframe

In [ ]:

dataframe['keywords'] = ""
allkey_list = []
for title in dataframe["course_title_l"]:
    keywords = kw_model.extract_keywords(title, keyphrase_ngram_range=(1,3), stop_words="english", highlight =False, top_n=10)
    keywords_list = list(dict(keywords).keys())
    #print(keywords_list)
    
    title_index = dataframe.index[dataframe["course_title_l"] == title].tolist()
    title_index = title_index[0]

    allkey_list.append(keywords_list)
    print(allkey_list)

In [44]:
dataframe = pandas.read_csv("courses_with_keywords_test.csv")
dataframe

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Simplified_Title,course_title_l,keywords
0,0,0,0,0,0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,TRUE,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,ultimate investment banking course,ultimate investment banking course,"['investment banking course', 'banking course'..."
1,1,1,1,1,1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,TRUE,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,complete gst course certification grow practice,complete gst course & certification - grow you...,"['gst course certification', 'complete gst cou..."
2,2,2,2,2,2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,TRUE,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,financial modeling business analysts consultants,financial modeling for business analysts and c...,"['financial modeling business', 'modeling busi..."
3,3,3,3,3,3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,TRUE,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,beginner pro financial analysis excel 2017,beginner to pro - financial analysis in excel ...,"['financial analysis excel', 'analysis excel 2..."
4,4,4,4,4,4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,TRUE,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,maximize profits trading options,how to maximize your profits trading options,"['profits trading options', 'maximize profits ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,3678,3678,3678,3678,3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,TRUE,100,1040,14,21,All Levels,2 hours,2016-06-14T17:36:46Z,Web Development,learn jquery scratch master javascript library,learn jquery from scratch - master of javascri...,"['learn jquery', 'learn jquery scratch', 'jque..."
3679,3679,3679,3679,3679,3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,TRUE,25,306,3,42,Beginner Level,3.5 hours,2017-03-10T22:24:30Z,Web Development,design wordpress website coding,how to design a wordpress website with no codi...,"['design wordpress website', 'wordpress websit..."
3680,3680,3680,3680,3680,3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,TRUE,40,513,169,48,All Levels,3.5 hours,2015-12-30T16:41:42Z,Web Development,learn build polymer,learn and build using polymer,"['build using polymer', 'using polymer', 'lear..."
3681,3681,3681,3681,3681,3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,TRUE,50,300,31,38,All Levels,3 hours,2016-08-11T19:06:15Z,Web Development,css animations create amazing effects website,css animations: create amazing effects on your...,"['css animations create', 'css animations', 'a..."
3682,3682,3682,3682,3682,3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,TRUE,45,901,36,20,Beginner Level,2 hours,2014-09-28T19:51:11Z,Web Development,modx cms build websites beginners guide,using modx cms to build websites: a beginner's...,"['modx cms', 'using modx cms', 'modx cms build..."

In [ ]:

user_input = "short selling"
result_keywords_list = []

for keyword_list in dataframe['keywords']:
    print(index)
    x = eval(keyword_list)
    print(type(x))
    index = dataframe.index[dataframe["keywords"] == keyword_list].tolist()

nan

In [ ]:
#keyword_list = list(map(str.strip, keyword_list.strip('][').replace('"', '').split(',')))
    #type(keyword_list)
    #for keyword in keyword_list:
        #print(keyword)
        
        #if user_input in keyword:
            #print(keyword)
            # result_keywords_list.append(keyword_list)

In [121]:
##keyword matching
result_dataframe = 0
user_input="excel portfolio"
user_input = user_input.lower()

keywords_user = kw_model.extract_keywords(user_input, keyphrase_ngram_range=(1,3), stop_words="english", highlight =False, top_n=10)
user_input_list = list(dict(keywords_user).keys())
print(user_input_list)

matched_keywords= {"course_title":[],"matched_values" :[]}            

for skeywords in dataframe['keywords']:
    
    keywords_list = eval(skeywords)
    
    matched_values = 0
    



                
    for keyword in user_input_list:
        if keyword in keywords_list:
            matched_values+=1
            title_index = dataframe.index[dataframe["keywords"] == str(keywords_list)].tolist()
            
            title_index = title_index[0]
            title = dataframe.loc[title_index,"course_title_l"]
            
           
    matched_keywords["course_title"].append(title)
    matched_keywords["matched_values"].append(matched_values)

result_dataframe = (pandas.DataFrame(matched_keywords)).sort_values(by=["matched_values"], ascending=False)
result_dataframe

['excel portfolio', 'portfolio', 'excel']

                                           course_title  matched_values
728            investment portfolio analysis with excel               2
967                    portfolio management cfa l1 2016               1
1084  excel 4 accounting & bookkeeping - master date...               1
912          matemática financeira com hp12c e ms excel               1
731   excel 4 accounting & bookkeeping - master look...               1
...                                                 ...             ...
1252  excel 4 accounting & bookkeeping - master date...               0
1253  excel 4 accounting & bookkeeping - master date...               0
1254  excel 4 accounting & bookkeeping - master date...               0
1255  excel 4 accounting & bookkeeping - master date...               0
3682  building a portfolio in 90 minutes ( html, css...               0

[3683 rows x 2 columns]

'ultimate investment banking course'

In [129]:
def recommendation_system(user_input):
    #Check is user input is empty
    if user_input =='':
        user_input = None
 

    #Get course id
    if user_input is not None:
        try:

            user_input = user_input.lower()
            id = course_id[user_input]

            #create similarity index for each course and sorting from highest to lowest
            sim_index = list(enumerate(cossim_matrix[id]))
            sorted_sindex = sorted(sim_index, key=lambda x:x[1],reverse = True)
            sorted_sindex[1:]

            #Picking Final courses to be displayed:
            final_courses = [i[0] for i in sorted_sindex[1:]]
            
                
            #final result
            result = dataframe['course_title_l'].iloc[final_courses]
            result_dataframe = pandas.DataFrame(result)
            print(result_dataframe)
        except:
            keywords_user = kw_model.extract_keywords(user_input, keyphrase_ngram_range=(1,3), stop_words="english", highlight =False, top_n=10)
            user_input_list = list(dict(keywords_user).keys())
            

            matched_keywords= {"course_title":[],"matched_values" :[]}            

            for skeywords in dataframe['keywords']:
    
                keywords_list = eval(skeywords)
    
                matched_values = 0
    



                
                for keyword in user_input_list:
                    if keyword in keywords_list:
                        matched_values+=1
                        title_index = dataframe.index[dataframe["keywords"] == str(keywords_list)].tolist()
            
                        title_index = title_index[0]
                        title = dataframe.loc[title_index,"course_title_l"]
            
           
                        matched_keywords["course_title"].append(title)
                        matched_keywords["matched_values"].append(matched_values)

            result_dataframe = (pandas.DataFrame(matched_keywords)).sort_values(by=["matched_values"], ascending=False)
            

    return result_dataframe

In [130]:
recommendation_system("excel")

                                         course_title  matched_values
0   beginner to pro - financial analysis in excel ...               1
1   beginner to pro in excel: financial modeling a...               1
22  excel 4 accounting & bookkeeping - master date...               1
21  optimize! make best decisions with microsoft e...               1
20          financial modelling in excel step by step               1
19              stock fundamental analysis with excel               1
18         matemática financeira com hp12c e ms excel               1
17           financial modeling in excel for startups               1
16  create your own automated stock trading robot ...               1
15                 bank reconciliation & vat on excel               1
14  financial and business simulation with microso...               1
13                       financial ratios using excel               1
12  excel 4 accounting & bookkeeping - master look...               1
11           investment portfolio analysis with excel               1
10  win 90% of trades; quantitative investments mo...               1
9                 stock technical analysis with excel               1
8   hands-on financial modeling (with 6 excel temp...               1
7                            advanced excel functions               1
6              building financial statements in excel               1
5       excel functions to analyze and visualize data               1
4    basic excel for basic bookkeeping and accounting               1
3   the power modeling bootcamp: advanced excel in...               1
2   excel crash course: master excel for financial...               1
23  photoshop: automatiza invitaciones con bloc de...               1

TypeError: type 'DataFrame' is not subscriptable