In [1]:
#Import required modules and functions
import pandas
import neattext.functions as nt_func
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [2]:
dataframe = pandas.read_csv("dataset/courses.csv")
dataframe.head()

,id,title,url,rating,num_reviews,num_published_lectures,created,last_update_date,duration,instructors_id,image
0,567828,The Complete Python Bootcamp From Zero to Hero...,/course/complete-python-bootcamp/,4.592782,452973,155,2015-07-29T00:12:23Z,2021-03-14,22 total hours,9685726,https://img-c.udemycdn.com/course/750x422/5678...
1,1565838,The Complete 2023 Web Development Bootcamp,/course/the-complete-web-development-bootcamp/,4.667258,263152,490,2018-02-22T12:02:33Z,2023-01-20,65.5 total hours,31334738,https://img-c.udemycdn.com/course/750x422/1565...
2,625204,The Web Developer Bootcamp 2023,/course/the-web-developer-bootcamp/,4.696147,254711,616,2015-09-28T21:32:19Z,2023-02-12,64 total hours,4466306,https://img-c.udemycdn.com/course/750x422/6252...
3,756150,Angular - The Complete Guide (2023 Edition),/course/the-complete-guide-to-angular-2/,4.592692,180257,472,2016-02-08T17:02:55Z,2023-02-06,34.5 total hours,13952972,https://img-c.udemycdn.com/course/750x422/7561...
4,2776760,100 Days of Code: The Complete Python Pro Boot...,/course/100-days-of-code/,4.695252,177568,676,2020-01-24T10:47:21Z,2022-11-30,64 total hours,31334738,https://img-c.udemycdn.com/course/750x422/2776...

In [3]:
dataframe.head()

,id,title,url,rating,num_reviews,num_published_lectures,created,last_update_date,duration,instructors_id,image
0,567828,The Complete Python Bootcamp From Zero to Hero...,/course/complete-python-bootcamp/,4.592782,452973,155,2015-07-29T00:12:23Z,2021-03-14,22 total hours,9685726,https://img-c.udemycdn.com/course/750x422/5678...
1,1565838,The Complete 2023 Web Development Bootcamp,/course/the-complete-web-development-bootcamp/,4.667258,263152,490,2018-02-22T12:02:33Z,2023-01-20,65.5 total hours,31334738,https://img-c.udemycdn.com/course/750x422/1565...
2,625204,The Web Developer Bootcamp 2023,/course/the-web-developer-bootcamp/,4.696147,254711,616,2015-09-28T21:32:19Z,2023-02-12,64 total hours,4466306,https://img-c.udemycdn.com/course/750x422/6252...
3,756150,Angular - The Complete Guide (2023 Edition),/course/the-complete-guide-to-angular-2/,4.592692,180257,472,2016-02-08T17:02:55Z,2023-02-06,34.5 total hours,13952972,https://img-c.udemycdn.com/course/750x422/7561...
4,2776760,100 Days of Code: The Complete Python Pro Boot...,/course/100-days-of-code/,4.695252,177568,676,2020-01-24T10:47:21Z,2022-11-30,64 total hours,31334738,https://img-c.udemycdn.com/course/750x422/2776...

In [4]:
#Simplified course names
dataframe["Simplified_Title"] = dataframe["title"].apply(nt_func.remove_stopwords)
dataframe.head()

,id,title,url,rating,num_reviews,num_published_lectures,created,last_update_date,duration,instructors_id,image,Simplified_Title
0,567828,The Complete Python Bootcamp From Zero to Hero...,/course/complete-python-bootcamp/,4.592782,452973,155,2015-07-29T00:12:23Z,2021-03-14,22 total hours,9685726,https://img-c.udemycdn.com/course/750x422/5678...,Complete Python Bootcamp Zero Hero Python
1,1565838,The Complete 2023 Web Development Bootcamp,/course/the-complete-web-development-bootcamp/,4.667258,263152,490,2018-02-22T12:02:33Z,2023-01-20,65.5 total hours,31334738,https://img-c.udemycdn.com/course/750x422/1565...,Complete 2023 Web Development Bootcamp
2,625204,The Web Developer Bootcamp 2023,/course/the-web-developer-bootcamp/,4.696147,254711,616,2015-09-28T21:32:19Z,2023-02-12,64 total hours,4466306,https://img-c.udemycdn.com/course/750x422/6252...,Web Developer Bootcamp 2023
3,756150,Angular - The Complete Guide (2023 Edition),/course/the-complete-guide-to-angular-2/,4.592692,180257,472,2016-02-08T17:02:55Z,2023-02-06,34.5 total hours,13952972,https://img-c.udemycdn.com/course/750x422/7561...,Angular - Complete Guide (2023 Edition)
4,2776760,100 Days of Code: The Complete Python Pro Boot...,/course/100-days-of-code/,4.695252,177568,676,2020-01-24T10:47:21Z,2022-11-30,64 total hours,31334738,https://img-c.udemycdn.com/course/750x422/2776...,100 Days Code: Complete Python Pro Bootcamp 2023

In [5]:
#Simplified course names
dataframe["Simplified_Title"] = dataframe["Simplified_Title"].apply(nt_func.remove_special_characters)

In [6]:
dataframe[["title", "Simplified_Title"]]

,title,Simplified_Title
0,The Complete Python Bootcamp From Zero to Hero...,Complete Python Bootcamp Zero Hero Python
1,The Complete 2023 Web Development Bootcamp,Complete 2023 Web Development Bootcamp
2,The Web Developer Bootcamp 2023,Web Developer Bootcamp 2023
3,Angular - The Complete Guide (2023 Edition),Angular Complete Guide 2023 Edition
4,100 Days of Code: The Complete Python Pro Boot...,100 Days Code Complete Python Pro Bootcamp 2023
...,...,...
83099,Was sind Subliminales und wie stelle ich sie h...,sind Subliminales und wie stelle ich sie her H...
83100,Introduction au Piano populaire (avec symboles...,Introduction au Piano populaire avec symboles ...
83101,あい先生のピアノレッスン 親子で学ぶピアノ準備編,
83102,Spielerisch Gitarre Spielen Lernen Für Anfänger,Spielerisch Gitarre Spielen Lernen Fr Anfnger
83103,クロマチックハーモニカをはじめる前に知っておきたいこと,

In [7]:
#Text Vectorization Process
cvector = CountVectorizer()
cvector_matrix = cvector.fit_transform(dataframe['Simplified_Title'])

In [9]:
dataframe_cv_words = pandas.DataFrame(cvector_matrix.todense(), columns = cvector.get_feature_names_out())

In [10]:
dataframe_cv_words.head()

,00,001,01,0100,010000,010111,010150,010160,010yrs,012,...,zusammenfhren,zusammenspiel,zwave,zwcad,zweite,zy,zye,zynq,zynq7000,zzpers
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0